### ISSUE TITLE
Could you please give your email ? I have some question about datasets

### ISSUE THREAD

**Issue by consolexinhun** [Raykoooo/CAC-UNet#3]

**Comment by bupt-ai-cz** [comment]
Please see, https://github.com/bupt-ai-cz/CAC-UNet

![image](https://user-images.githubusercontent.com/76641042/127593810-a66f17df-454b-4b8f-95e0-fa7b32351780.png)

Regarding the data, email Hongsheng Li: hsli@ee.cuhk.edu.hk

If you have more questions, contact here:
https://github.com/bupt-ai-cz/CAC-UNet
